export enum PaymentStatus {
  CREATED = "CREATED",
  WAITING_DEVICE = "WAITING_DEVICE",
  CARD_INSERTED = "CARD_INSERTED",
  PROCESSING = "PROCESSING",
  AUTHORIZED = "AUTHORIZED",
  CONFIRMED = "CONFIRMED",
  FINISHED = "FINISHED",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",
  TIMEOUT = "TIMEOUT",
  COMMUNICATION_ERROR = "COMMUNICATION_ERROR"
}
