import { AlertTriangle, ArrowDown, ArrowUp, Boxes, History, PackagePlus, Pencil, RefreshCw, Search, SlidersHorizontal, WalletCards, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Sidebar } from "../components/Sidebar";
import { Topbar } from "../components/Topbar";
import { useToast } from "../components/feedback/ToastProvider";
import { normalizeApiError } from "../services/api/api-error";
import { inventoryService, type InventoryInput, type InventoryItem, type InventoryMovement, type InventoryUnit, type MovementType } from "../services/api/inventory.service";
import { formatCurrency } from "../utils/currency";
const units:Record<InventoryUnit,string>={KG:"kg",G:"g",L:"L",ML:"mL",UNIT:"un"};
const blank:InventoryInput={name:"",category:"",unit:"UNIT",currentStock:0,minimumStock:0,unitCost:0,supplier:null};
export function InventoryPage(){
 const toast=useToast();const[items,setItems]=useState<InventoryItem[]>([]);const[movements,setMovements]=useState<InventoryMovement[]>([]);const[summary,setSummary]=useState({total:0,lowStock:0,totalValue:0,categories:0});const[loading,setLoading]=useState(true);const[q,setQ]=useState("");const[lowOnly,setLowOnly]=useState(false);const[editor,setEditor]=useState<InventoryItem|null|"new">(null);const[moving,setMoving]=useState<InventoryItem|null>(null);
 async function load(){setLoading(true);try{const[a,b]=await Promise.all([inventoryService.list({q:q||undefined,lowStock:lowOnly||undefined}),inventoryService.movements()]);setItems(a.data);setSummary(a.summary);setMovements(b.data);}catch(e){toast.error(normalizeApiError(e).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[lowOnly]);
 const categories=useMemo(()=>Array.from(new Set(items.map(i=>i.category))),[items]);
 return <main className="dashboard-layout"><Sidebar/><section className="dashboard-main"><Topbar actions={<button className="button button--soft" onClick={()=>void load()} disabled={loading}><RefreshCw size={17} className={loading?"icon-spin":undefined}/>Atualizar</button>}/><div className="dashboard-content inventory-page">
 <div className="page-heading"><div><span className="eyebrow">Gestão</span><h1>Estoque</h1><p>Controle insumos, saldos mínimos e movimentações da cafeteria.</p></div><button className="button button--primary" onClick={()=>setEditor("new")}><PackagePlus size={17}/>Novo item</button></div>
 <div className="inventory-summary"><Summary icon={Boxes} label="Itens ativos" value={String(summary.total)}/><Summary icon={AlertTriangle} label="Estoque baixo" value={String(summary.lowStock)} danger={summary.lowStock>0}/><Summary icon={WalletCards} label="Valor estimado" value={formatCurrency(summary.totalValue)}/><Summary icon={SlidersHorizontal} label="Categorias" value={String(summary.categories)}/></div>
 <div className="inventory-toolbar"><label className="inventory-search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void load()} placeholder="Buscar item, categoria ou fornecedor"/>{q&&<button onClick={()=>{setQ("");setTimeout(()=>void load(),0)}}><X size={15}/></button>}</label><button className={lowOnly?"button button--soft inventory-filter--active":"button button--soft"} onClick={()=>setLowOnly(v=>!v)}><AlertTriangle size={16}/>Somente críticos</button><button className="button button--soft" onClick={()=>void load()}>Buscar</button></div>
 <section className="inventory-table-card"><div className="inventory-table-wrap"><table className="inventory-table"><thead><tr><th>Item</th><th>Categoria</th><th>Saldo</th><th>Mínimo</th><th>Custo</th><th>Fornecedor</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id} className={item.isLowStock?"inventory-row--low":""}><td><strong>{item.name}</strong>{item.isLowStock&&<span className="stock-badge"><AlertTriangle size={12}/>Baixo</span>}</td><td>{item.category}</td><td><b>{fmt(item.currentStock)} {units[item.unit]}</b></td><td>{fmt(item.minimumStock)} {units[item.unit]}</td><td>{formatCurrency(item.unitCost)}</td><td>{item.supplier||"—"}</td><td><div className="table-actions"><button title="Movimentar" onClick={()=>setMoving(item)}><ArrowUp size={15}/><ArrowDown size={15}/></button><button title="Editar" onClick={()=>setEditor(item)}><Pencil size={16}/></button></div></td></tr>)}{!loading&&!items.length&&<tr><td colSpan={7}><div className="inventory-empty"><Boxes size={34}/><strong>Nenhum item encontrado</strong><span>Cadastre o primeiro insumo ou ajuste os filtros.</span></div></td></tr>}</tbody></table></div></section>
 <section className="dashboard-panel inventory-history"><header><div><span className="panel-eyebrow">Auditoria</span><h2>Movimentações recentes</h2></div><History size={20}/></header><div className="movement-list">{movements.slice(0,12).map(m=><div key={m.id}><span className={`movement-icon movement-icon--${m.type.toLowerCase()}`}>{m.type==="ENTRY"?<ArrowUp size={16}/>:m.type==="EXIT"?<ArrowDown size={16}/>:<SlidersHorizontal size={16}/>}</span><div><strong>{labelType(m.type)} · {m.item.name}</strong><span>{m.user.name}{m.note?` — ${m.note}`:""}</span></div><b>{m.type==="EXIT"?"−":m.type==="ENTRY"?"+":"="}{fmt(m.quantity)} {units[m.item.unit]}</b><time>{new Date(m.createdAt).toLocaleString("pt-BR")}</time></div>)}{!movements.length&&<div className="inventory-empty"><History size={30}/><span>Nenhuma movimentação registrada.</span></div>}</div></section>
 </div></section>{editor&&<ItemModal item={editor==="new"?null:editor} categories={categories} onClose={()=>setEditor(null)} onSaved={()=>{setEditor(null);void load()}}/>}{moving&&<MovementModal item={moving} onClose={()=>setMoving(null)} onSaved={()=>{setMoving(null);void load()}}/>}</main>
}
function Summary({icon:Icon,label,value,danger}:{icon:typeof Boxes;label:string;value:string;danger?:boolean}){return <div className={danger?"inventory-summary-card inventory-summary-card--danger":"inventory-summary-card"}><Icon size={21}/><div><span>{label}</span><strong>{value}</strong></div></div>}
function ItemModal({item,categories,onClose,onSaved}:{item:InventoryItem|null;categories:string[];onClose:()=>void;onSaved:()=>void}){const toast=useToast();const[form,setForm]=useState<InventoryInput>(item?{name:item.name,category:item.category,unit:item.unit,currentStock:item.currentStock,minimumStock:item.minimumStock,unitCost:item.unitCost,supplier:item.supplier}:blank);const[saving,setSaving]=useState(false);async function save(){if(!form.name.trim()||!form.category.trim()){toast.warning("Informe nome e categoria.");return}setSaving(true);try{item?await inventoryService.update(item.id,{...form,currentStock:undefined}):await inventoryService.create(form);toast.success(item?"Item atualizado.":"Item cadastrado.");onSaved()}catch(e){toast.error(normalizeApiError(e).message)}finally{setSaving(false)}}return <div className="modal-backdrop"><div className="modal-card inventory-modal"><header><div><span className="eyebrow">Estoque</span><h2>{item?"Editar item":"Novo item"}</h2></div><button onClick={onClose}><X/></button></header><div className="inventory-form"><Field label="Nome *" value={form.name} onChange={v=>setForm({...form,name:v})}/><label><span>Categoria *</span><input list="inventory-categories" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><datalist id="inventory-categories">{categories.map(c=><option key={c}>{c}</option>)}</datalist></label><label><span>Unidade</span><select value={form.unit} onChange={e=>setForm({...form,unit:e.target.value as InventoryUnit})}>{Object.entries(units).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>{!item&&<Field label="Saldo inicial" type="number" value={String(form.currentStock)} onChange={v=>setForm({...form,currentStock:Number(v)})}/>}<Field label="Estoque mínimo" type="number" value={String(form.minimumStock)} onChange={v=>setForm({...form,minimumStock:Number(v)})}/><Field label="Custo unitário" type="number" value={String(form.unitCost)} onChange={v=>setForm({...form,unitCost:Number(v)})}/><Field label="Fornecedor" value={form.supplier||""} onChange={v=>setForm({...form,supplier:v||null})}/></div><footer><button className="button button--soft" onClick={onClose}>Cancelar</button><button className="button button--primary" disabled={saving} onClick={()=>void save()}>{saving?"Salvando...":"Salvar"}</button></footer></div></div>}
function MovementModal({item,onClose,onSaved}:{item:InventoryItem;onClose:()=>void;onSaved:()=>void}){const toast=useToast();const[type,setType]=useState<MovementType>("ENTRY");const[quantity,setQuantity]=useState(0);const[note,setNote]=useState("");const[saving,setSaving]=useState(false);async function save(){if(type!=="ADJUSTMENT"&&quantity<=0){toast.warning("Informe uma quantidade maior que zero.");return}setSaving(true);try{await inventoryService.move(item.id,{type,quantity,note:note||null});toast.success("Movimentação registrada.");onSaved()}catch(e){toast.error(normalizeApiError(e).message)}finally{setSaving(false)}}return <div className="modal-backdrop"><div className="modal-card inventory-modal inventory-movement-modal"><header><div><span className="eyebrow">Movimentação</span><h2>{item.name}</h2><p>Saldo atual: <b>{fmt(item.currentStock)} {units[item.unit]}</b></p></div><button onClick={onClose}><X/></button></header><div className="movement-type-picker">{(["ENTRY","EXIT","ADJUSTMENT"] as MovementType[]).map(v=><button key={v} className={type===v?"movement-type movement-type--active":"movement-type"} onClick={()=>setType(v)}>{labelType(v)}</button>)}</div><div className="inventory-form inventory-form--single"><Field label={type==="ADJUSTMENT"?"Novo saldo":"Quantidade"} type="number" value={String(quantity)} onChange={v=>setQuantity(Number(v))}/><label><span>Observação</span><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Motivo ou referência da movimentação"/></label></div><footer><button className="button button--soft" onClick={onClose}>Cancelar</button><button className="button button--primary" disabled={saving} onClick={()=>void save()}>{saving?"Registrando...":"Registrar"}</button></footer></div></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label><span>{label}</span><input type={type} min={type==="number"?0:undefined} step={type==="number"?"0.001":undefined} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function fmt(v:number){return new Intl.NumberFormat("pt-BR",{maximumFractionDigits:3}).format(v)}function labelType(v:MovementType){return v==="ENTRY"?"Entrada":v==="EXIT"?"Saída":"Ajuste"}
