ALTER TABLE "companies"
  ADD COLUMN "state_registration" TEXT,
  ADD COLUMN "tax_regime" TEXT,
  ADD COLUMN "cnae" TEXT,
  ADD COLUMN "postal_code" TEXT,
  ADD COLUMN "street" TEXT,
  ADD COLUMN "address_number" TEXT,
  ADD COLUMN "address_complement" TEXT,
  ADD COLUMN "neighborhood" TEXT,
  ADD COLUMN "city" TEXT,
  ADD COLUMN "state" TEXT,
  ADD COLUMN "phone" TEXT,
  ADD COLUMN "whatsapp" TEXT,
  ADD COLUMN "email" TEXT,
  ADD COLUMN "website" TEXT,
  ADD COLUMN "display_name" TEXT,
  ADD COLUMN "logo_data_url" TEXT,
  ADD COLUMN "primary_color" TEXT NOT NULL DEFAULT '#6A4E3B',
  ADD COLUMN "receipt_footer" TEXT NOT NULL DEFAULT 'Obrigado pela preferência!',
  ADD COLUMN "print_logo" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "print_document" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "print_address" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "print_phone" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN "language" TEXT NOT NULL DEFAULT 'pt-BR',
  ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'BRL',
  ADD COLUMN "timezone" TEXT NOT NULL DEFAULT 'America/Fortaleza';
